### ISSUE TITLE
Problema com a versão dos DCUs

### ISSUE THREAD

**Issue by igorbastosib** [CarlosHe/AndroidPermission#2]
Acredito que o erro seja questão de compilação das Units afetadas pelas alterações, estou recebendo o erro:
 F2051 Unit FMX.WebBrowser.Android was compiled with a different version of FMX.Platform.Android.MainActivity

O erro inicialmente aconteceu qnd tentei compilar o nosso projeto real após as alterações. Depois testei com o projeto Demo e aconteceu tbm.

Fiz os procedimentos como diz o tutorial, executei o projeto demo e deu super certo, mas ao inserir um TabControl no Form1 (do projeto Demo) o erro já aparece.

Como solucionar?

**Comment by welsoncj** [comment]
por acaso sumiu o caminho do library path la em Tools - Options?

**Comment by CarlosHe** [comment]
Já encontra-se resolvido! É só baixar e reaplicar o patch!

**Comment by sigalle** [comment]
nao compila mais meu projeto
[DCC Fatal Error] U_main.pas(9): F2613 Unit 'FMX.WebBrowser.Android' not found.
  U_main.pas(9): Unit 'FMX.WebBrowser.Android' is used by 'FMX.WebBrowser'
  U_main.pas(9): Unit 'FMX.WebBrowser' is used by 'FMX.TabControl'

no seu, igual
Fiz os procedimentos como diz o tutorial, executei o projeto demo e deu super certo, mas ao inserir um TabControl no Form1 (do projeto Demo) o erro já aparece.

e agora? Auxilio. Meu projeto ja estaba pronto e agora nao compila mais

**Comment by CarlosHe** [comment]
Vou corrigir essas duas e já mando a atualização
